### ISSUE TITLE
One simple question 

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/h-transformer-1d#10]
Hi, Phil!

One simple question, (my math is not good)
https://github.com/lucidrains/h-transformer-1d/blob/7c11d036d53926495ec0917a34a1aad7261892b5/train.py#L65

why not be `randint(0, self.data.size(0)-self.seq_len+1)`? Since the high part should be excluded

**Comment by lucidrains** [comment]
@CiaoHe Hey! I believe you are right and made the change https://github.com/lucidrains/h-transformer-1d/commit/9c09a00a946ab12e0820f56ebaa21bfb8bb28fcf the extra  `- 1` was actually to account for fetching sequence length + 1 for being broken up into input and labels

**Comment by CiaoHe** [comment]
wow i see! thank you !
