### ISSUE TITLE
H-Transformer for Cross-Attention?

### ISSUE THREAD

**Issue by Vbansal21** [lucidrains/h-transformer-1d#2]
Is it possible to use this architecture for Cross attention?

**Comment by lucidrains** [comment]
It's not unfortunately :(

**Comment by Vbansal21** [comment]
What if the the code was altered to make it support cross attention? Would that give any meaningful result?

**Comment by lucidrains** [comment]
@Vbansal21 it's not possible, since there is no notion of locality between the source and target

**Comment by Vbansal21** [comment]
Okay. Well, then closing this issue.
