### ISSUE TITLE
ModuleNotFoundError: No module named 'rotary_embedding_torch'

### ISSUE THREAD

**Issue by wajihullahbaig** [lucidrains/h-transformer-1d#5]
**"/Personal/Codes/h-transformer-1d/h_transformer_1d/h_transformer_1d.py", line 6, in <module>
    from rotary_embedding_torch import apply_rotary_emb, RotaryEmbedding"**

Seems there is a module that was not committed to the repo.

**Comment by lucidrains** [comment]
make sure you run `pip install h-transformer-1d` first! or `pip install rotary-embedding-torch`
