### ISSUE TITLE
eos token does not work in batch mode generation

### ISSUE THREAD

**Issue by tmphex** [lucidrains/h-transformer-1d#9]
When generating the sequence with current code it seems the `eos_token` will work when generating one sequence at a time https://github.com/lucidrains/h-transformer-1d/blob/main/h_transformer_1d/autoregressive_wrapper.py#L59

**Comment by lucidrains** [comment]
ohh, this is indeed a bug, and i'll fix this today

**Comment by lucidrains** [comment]
@tmphex let me know if this https://github.com/lucidrains/h-transformer-1d/commit/e3cb1afee7a1c8895180d89aa3a9c51ef42c8d3a works for you

**Comment by tmphex** [comment]
Thanks @lucidrains for fixing it quickly. I think its the same issue in `x-transformers` repo too. https://github.com/lucidrains/x-transformers/blob/main/x_transformers/autoregressive_wrapper.py#L80

**Comment by lucidrains** [comment]
> Thanks @lucidrains for fixing it quickly. I think its the same issue in `x-transformers` repo too. https://github.com/lucidrains/x-transformers/blob/main/x_transformers/autoregressive_wrapper.py#L80

haha yup, i'll fix it there too
